### ISSUE TITLE
破解方法x2

### ISSUE THREAD

**Issue by ChenYFan** [MHuiG/timing-sampling-devtools-detect#2]
对setInterval函数直接hook进行防抖即可，样例代码懒得写了。

此外，当标签页被切时，chrome的setinterval周期会拉至2s，可能会误判

**Comment by MHuiG** [comment]
当然如果你对破解和反破解感兴趣，我可以给你一个写入权限，你自己改一下。

**Comment by MHuiG** [comment]
还有一点，对setInterval函数hook时机必须要在计时器启动前的位置然后进行hook，不然就是无效的。

假设可以在计时器启动前的位置然后进行hook，那为什么不直接把判断代码删掉呢，这显然是没有意义的。

![image](https://user-images.githubusercontent.com/38281581/176569206-d6390f3c-8ad7-44c6-8078-2aed86a86366.png)

**Comment by ChenYFan** [comment]
> 当然如果你对破解和反破解感兴趣，我可以给你一个写入权限，你可以帮忙改一下。

额，其实我是觉得通过console占用资源判断控制台的打开是一个非常有趣的思路才会关注这个的，并不是故意过来找茬的

**Comment by MHuiG** [comment]
实际上这个东西是用于添加调试辅助信息的，像是控制台打开的时候页面上添加辅助线，辅助样式之类的便于调试，当然涉及到破解的话，你应该是想干一些其他的什么事情。

**Comment by MHuiG** [comment]
我试着搞了一下，这种 hook 函数的破解方法，看看有没有问题。
